openapi: 3.0.0
info:
  title: Authentication App API
  description: API documentation for the Authentication App.
  version: 1.0.0
  contact:
    name: API Support
    url: https://authapp-qdzy.onrender.com/
    email: support@example.com
servers:
  - url: http://localhost:3000/api/v1
    description: Local development server

paths:
  /:
    get:
      summary: Home
      description: Returns a welcome message.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /api/v1/signup:
    post:
      summary: User Sign-up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: User created successfully

  /api/v1/login:
    post:
      summary: User Login
      tags:
        - Public Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: User logged in successfully
          content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                token:
                  type: string
                user:
                  $ref: '#/components/schemas/User'
        '401':
          description: Invalid credentials

  /api/v1/test:
    get:
      summary: Test Route
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Authenticated access

  /api/v1/student:
    get:
      summary: Student Route
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Accessible to users with "Student" role
        '401':
          description: Forbidden

  /api/v1/admin:
    get:
      summary: Admin Route
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Accessible to users with "Admin" role
        '403':
          description: Forbidden

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      required:
        - name
        - email
        - password
        - role
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
          enum: [Admin, Student, Visitor]

tags:
  - name: Public Endpoints
  - name: Protected Endpoints
